### PR TITLE
Louisl/feature/movie support, closes #243

### PR DESCRIPTION
**Pull request by sadok-f**
Followup PR to #243

### CODE REVIEW

**Comment by sadok-f** [comment]
@louisl could you please work to add small documentation to the README file?

**Comment by louisl** [comment]
OK, working on the README.

**Comment by louisl** [comment]
> @louisl could you please work to add small documentation to the README file?

Updated in #245

**Comment by sadok-f** [comment]
All green now 👍 
Thank you @louisl !

**Comment by louisl** [comment]
@sadok-f Hi I think you merged #244 before merging #245 so the README didn't get updated or are you working on that?

**Pull request merged**
