### PR TITLE
Add colorspace and monochrome options , Issue#299

### PR DESCRIPTION
**Pull request by sadok-f**
Add colorspace and monochrome options , Issue#299

### CODE REVIEW

**Comment by diego-vieira** [comment]
@sadok-f just thought I'd let you know that version 1.1.25 is broken with the following

`The exit code: convert: unrecognized image colorspace `-filter' @`

Screenshot 2021-01-18 at 23 02 37 563


1.1.24 is working fine.

Many thanks

**Comment by sadok-f** [comment]
Hey @diego-vieira,
Thank you for reporting the issue, I wasn't able to reproduce the issue though.
Can you check your config/parameters.yml file, the new version added new configs for `colorspace` (default to `sRGB`) which could be missing in your file.
Thanks again.

**Comment by diego-vieira** [comment]
@sadok-f that was indeed the case, I've updated the missing settings and it's all good.

Many thanks

**Comment by sadok-f** [comment]
Great!
You're welcome :)

**Pull request merged**
