### PR TITLE
Update branch deployments

### PR DESCRIPTION
**Pull request by GrantBirki**
👋 Hey folks! I am the creator and main maintainer for the branch-deploy Action. I saw that you were using it and wanted to bring in some improvements.

I have done the following:

- Upgraded to `v9`. It should be safe for you to do so in this project (I checked)
- Added a more specific `if:` block to help prevent excess Actions workflows to trigger when folks leave comments on PRs that don't contain `.deploy` style commands
- Added an extra permissions statement (only really applies to private repos but its safe to add here)

### CODE REVIEW

**Comment by sadok-f** [comment]
Thank you @GrantBirki for your PR and the work you're doing on the branch-deploy action!
We're happy to accept it

**Comment by sadok-f** [comment]
.deploy

**Comment by GrantBirki** [comment]
@sadok-f after merging this PR, open a fresh one with little to no changes and try the `.deploy` command just to ensure that it works as expected once changes land on `main`

**Comment by sadok-f** [comment]
@GrantBirki I've tested it and it worked as expected.
Thank you!

**Pull request merged**
