### PR TITLE
Update docs, I'm separating the content in the readme and resorting URL parameters.

### PR DESCRIPTION
**Pull request by baamenabar**
Don't merge yet
#88

### CODE REVIEW

**Comment by baamenabar** [comment]
Can we tag this Pull Request as part of a 1.x release?

**Comment by baamenabar** [comment]
All right! @sadok-f take a look. I added 2 files to the docs. 
If you like it, let me know and we merge it.

**Comment by sadok-f** [comment]
@baamenabar Great job!
There are some minor changes I'll request, but overall awesome work!

**Comment by sadok-f** [comment]
@baamenabar Great!
+1 merge it !

**Pull request merged**
