### PR TITLE
Use new deploy redirector

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by sadok-f** [comment]
Hi @jamesward ,
Thank you for submitting this PR!
I'm gonna merge it, although until now we're not able to run the project in Google cloud, due the to this open issue: 
https://github.com/google/gvisor/issues/139

**Comment by ahmetb** [comment]
Note that the redirector is not going to work from http://flyimg.io/
We should add ?git_repo.

@sadok-f I'm also eagerly waiting for signalfd fixes so I can write a s6 tutorial!

**Comment by jamesward** [comment]
Does the readme get used on flyimg.io or do we need to update another file?

**Comment by jamesward** [comment]
Oh! Seeing Ahmet's other PR.  Nice :)

**Comment by peterzandbergen** [comment]
Hi James,
I merged your pull request and imported the github repo in GitLab.: https://gitlab.com/peterzandbergen/myipaddress


When I click on the run button I get this message:

```
Cannot infer which repository to deploy (Referer header was not present).
Go back, and click the 'Run on Google Cloud' button directly from the repository page.
```

This may be caused by the attributes of the a element of the button (nofollow, noreferrer noopener)

```
<a href="https://deploy.cloud.run" rel="nofollow noreferrer noopener" target="_blank">
    <img src="https://user-content.gitlab-static.net/92ec1bd61ce4fa532cf26f2b490600f7ece21d77/68747470733a2f2f6465706c6f792e636c6f75642e72756e2f627574746f6e2e737667" alt="Run on Google Cloud" data-canonical-src="https://deploy.cloud.run/button.svg" class="js-lazy-loaded qa-js-lazy-loaded">
</a>
```

**Comment by jamesward** [comment]
Ah, yeah.  The redirector uses the referer header.  You can add a `git_url` url param to override the referer detection.

**Pull request merged**
