### PR TITLE
Image Processor geometry refactor.

### PR DESCRIPTION
**Pull request by baamenabar**
this is just the first steps, the failing tests, I'll start the actual refactor after this.

### CODE REVIEW

**Comment by baamenabar** [comment]
More broken tests, but the ones passing are already with the refactored code. All horrible still. many methods will probably not make it to the final commit.... we'll see.

At least I'm clear now on how to do many of the operations in Imagemagick

**Comment by baamenabar** [comment]
**All tests passing again!** Added a bunch of new ones (more than 500 assertions in that module). Will add some more cases.

**Comment by baamenabar** [comment]
I did some cleanup, separated the super long test provider into two.  All green except that CodeClimate is being a Dick about a test. I don't have access to deactivate the warning or I'm out of ideas. The code it's complaining about stuff that should be similar, but would be weird to abstract.

For now I'm quite happy with the code. This week I'll start with a frontend module to have as a companion, after that I'll have some more use cases for the geometry module.

**Comment by sadok-f** [comment]
@baamenabar  you did a great job with this refactor part !
Keep going!

**Pull request merged**
